name: Build

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  Build_Test_Coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set Python Version
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install Dependencies
      run: |
        pip install wheel
        pip install -r requirements.txt
    - name: Build and Test
      run: python -m pytest --cov-config .coveragerc --cov=openconcept
    - name: Push to Coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: coveralls --service=github --rcfile=.coveragerc;
